using Avalonia;
using Avalonia.Controls;
namespace Pixel_Wall_E.ViewModels;
public partial class MainWindowViewModel : Window
{
    public MainWindowViewModel()
    {
        InitializeComponent();
    }
}

// in auto-generated by Avalonia.NameGenerator MainWindow.g.cs:
partial class MainWindowViewModel
{
    // ...
    public void InitializeComponent(bool loadXaml = true, bool attachDevTools = true)
    {
        // ...
#if DEBUG
        if (attachDevTools)
        {
            this.AttachDevTools();
        }
#endif
        // ...
    }
}